In [1]:
import pandas as pd
import json
import requests

In [2]:
# read dataframe
df_test = pd.read_csv('./data/target_apartments.csv')
df_test = df_test[:100].copy()

In [3]:
# convert Dataframe to json
df_json = df_test.to_dict( orient='records' )
df_json.append({'budget' : 20000000})
data = json.dumps(df_json)
df_test.head()

,rooms,garages,useful_area,latitude,longitude,value,interior_quality
0,2.0,1.0,57,-23.611514,-46.630069,454377,2
1,3.0,2.0,120,-23.560286,-46.664317,1500960,1
2,2.0,2.0,80,-23.563254,-46.696559,1045980,3
3,3.0,4.0,500,-23.509760,-46.650741,3707770,3
4,3.0,2.0,122,-23.520498,-46.723220,1007670,2

In [4]:
# API Call
# url = 'http://192.168.0.7:5000/portfolio/predict'
url = 'https://apartment-liquidity-pricing.herokuapp.com/portfolio/predict'
header = {'Content-type': 'application/json' }

r = requests.post( url, data=data, headers=header )
print( 'Status Code {}'.format( r.status_code ) )

Status Code 200

In [5]:
d1 = pd.DataFrame(r.json(), columns=r.json()[0].keys())

In [6]:
d1

,index,sale_price,obs,rooms,garages,useful_area,latitude,longitude,value,interior_quality,latitude_bins,longitude_bins,lat_long_bins,rooms_garages
0,17,330273.0,sem_reforma,2.0,1.0,45,-23.643029,-46.602321,220182,2,0,2,02,3.0
1,31,352420.5,sem_reforma,1.0,1.0,33,-23.588729,-46.632771,234947,3,1,2,12,2.0
2,80,705291.0,sem_reforma,2.0,1.0,84,-23.531996,-46.705390,470194,1,2,0,20,3.0
3,16,471046.5,sem_reforma,2.0,1.0,64,-23.610465,-46.625535,314031,2,0,2,02,3.0
4,67,885059.0,sem_reforma,2.0,1.0,124,-23.571537,-46.619960,632185,1,1,2,12,3.0
5,98,526321.5,sem_reforma,2.0,1.0,55,-23.634826,-46.637491,350881,1,0,2,02,3.0
6,40,577729.6,sem_reforma,2.0,1.0,70,-23.524329,-46.709350,412664,1,2,0,20,3.0
7,26,579919.5,sem_reforma,2.0,1.0,51,-23.618298,-46.632550,386613,2,0,2,02,3.0
8,13,471275.0,sem_reforma,2.0,1.0,48,-23.559398,-46.620859,336625,3,2,2,22,3.0
9,20,1988940.0,sem_reforma,4.0,4.0,241,-23.620885,-46.733079,1325960,2,0,0,00,8.0
10,12,1975785.0,sem_reforma,4.0,4.0,220,-23.636667,-46.730000,1317190,1,0,0,00,8.0
11,8,1636935.0,sem_reforma,3.0,4.0,187,-23.636608,-46.735320,1091290,2,0,0,00,7.0
12,0,590690.1,sem_reforma,2.0,1.0,57,-23.611514,-46.630069,454377,2,0,2,02,3.0
13,9,699938.4,sem_reforma,3.0,2.0,71,-23.542092,-46.569988,499956,2,2,2,22,5.0
14,90,1791114.0,sem_reforma,4.0,2.0,160,-23.570233,-46.634738,1377780,1,1,2,12,6.0
15,56,1286182.3,sem_reforma,3.0,1.0,140,-23.540877,-46.706460,989371,2,2,0,20,4.0
16,73,1080492.4,sem_reforma,3.0,2.0,110,-23.569139,-46.728255,831148,1,1,0,10,5.0
17,76,1845060.0,sem_reforma,4.0,3.0,198,-23.615671,-46.732592,1230040,3,0,0,00,7.0
18,43,1409590.0,sem_reforma,3.0,3.0,152,-23.634887,-46.737590,1006850,3,0,0,00,6.0
19,86,1434258.0,sem_reforma,4.0,3.0,149,-23.549925,-46.569688,1024470,2,2,2,22,7.0
20,49,1547955.0,sem_reforma,3.0,3.0,130,-23.644385,-46.670937,1031970,3,0,1,01,6.0
21,59,813013.6,sem_reforma,2.0,1.0,75,-23.596535,-46.645581,580724,2,1,2,12,3.0
22,6,1959074.0,sem_reforma,3.0,2.0,207,-23.578113,-46.590425,1506980,2,1,2,12,5.0
23,38,900232.5,sem_reforma,2.0,1.0,72,-23.576523,-46.644499,600155,2,1,2,12,3.0
24,62,1684110.0,sem_reforma,3.0,2.0,126,-23.583560,-46.629028,1122740,1,1,2,12,5.0
25,37,591204.6,sem_reforma,2.0,2.0,47,-23.601951,-46.606441,422289,3,0,2,02,4.0

In [7]:
d1['value'].sum()

19771612